### ISSUE TITLE
[templates-crm] internal server error when first running deno task start after forking template

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#71]
Error related to a cycle detection in the route handling or page rendering process. The error is originating from the @preact/signals-core module and seems to be related to the handling of signals within your application.

`
%cAn error occurred during route handling or page rendering.
Error: Cycle detected
    at v (https://esm.sh/v135/@preact/signals-core@1.5.0/X-ZS8q/denonext/signals-core.mjs:2:20)
    at c.S (https://esm.sh/v135/@preact/signals-core@1.5.0/X-ZS8q/denonext/signals-core.mjs:2:3857)
    at _ (https://esm.sh/v131/@preact/signals@1.2.1/X-ZS8q/denonext/signals.mjs:2:414)
    at https://esm.sh/v131/@preact/signals@1.2.1/X-ZS8q/denonext/signals.mjs:2:1320
    at options.__r (https://deno.land/x/fresh@1.6.1/src/server/rendering/preact_hooks.ts:445:3)
    at https://esm.sh/v135/@preact/signals@1.2.1/X-ZS8q/denonext/signals.mjs:2:1325
    at a.__r (https://esm.sh/stable/preact@10.19.2/denonext/debug.js:9:335)
    at a.__r (https://esm.sh/stable/preact@10.19.2/denonext/debug.js:30:98)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3228)
    at j (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:1742)
`

**Comment by gabrielromk** [comment]
new version available `@preact/signals-core@1.5.1`

**Comment by miguelrk** [comment]
Couldn't reporoduce this. Feel free to reopen if you come across this again. For new users, try running `deno upgrade` as well as `netzo upgrade` in case you stumble with this in the future.
